// Generated from RapidKL's official GTFS static feed
// (https://developer.data.gov.my/realtime-api/gtfs-static, category=rapid-rail-kl)
// via scripts/generate-stations.mjs — covers LRT, MRT, KL Monorail, and
// BRT Sunway. Don't hand-edit; re-run the script if the source changes.

export const LINES = [
  {
    "id": "ampang",
    "name": "LRT Ampang Line",
    "stations": [
      "Ampang",
      "Cahaya",
      "Cempaka",
      "Pandan Indah",
      "Pandan Jaya",
      "Maluri",
      "Miharja",
      "Chan Sow Lin",
      "Pudu",
      "Hang Tuah",
      "Plaza Rakyat",
      "Masjid Jamek",
      "Bandaraya - UOB",
      "Sultan Ismail",
      "PWTC",
      "Titiwangsa",
      "Sentul",
      "Sentul Timur"
    ]
  },
  {
    "id": "kelana-jaya",
    "name": "LRT Kelana Jaya Line",
    "stations": [
      "Putra Heights",
      "Subang Alam",
      "Alam Megah",
      "USJ 21",
      "Wawasan",
      "Taipan",
      "USJ 7",
      "SS 18",
      "SS 15",
      "Subang Jaya",
      "Glenmarie",
      "Ara Damansara",
      "Lembah Subang",
      "Kelana Jaya",
      "Taman Bahagia",
      "Taman Paramount",
      "Asia Jaya",
      "Taman Jaya",
      "Universiti",
      "Kerinchi",
      "Abdullah Hukum",
      "Bangsar - Bank Rakyat",
      "KL Sentral",
      "Pasar Seni",
      "Masjid Jamek",
      "Dang Wangi",
      "Kampung Baru - CBP Coopbank Pertama",
      "KLCC",
      "Ampang Park",
      "Damai",
      "Dato' Keramat",
      "Jelatek",
      "Setiawangsa",
      "Sri Rampai",
      "Wangsa Maju",
      "Taman Melati",
      "Gombak"
    ]
  },
  {
    "id": "sri-petaling",
    "name": "LRT Sri Petaling Line",
    "stations": [
      "Putra Heights",
      "Puchong Prima",
      "Puchong Perdana",
      "Bandar Puteri",
      "Taman Perindustrian Puchong",
      "Pusat Bandar Puchong",
      "IOI Puchong Jaya",
      "Kinrara",
      "Alam Sutera",
      "Muhibbah",
      "Awan Besar",
      "Sri Petaling",
      "Bukit Jalil",
      "Sungai Besi",
      "Bandar Tasik Selatan",
      "Bandar Tun Razak",
      "Salak Selatan",
      "Cheras",
      "Chan Sow Lin",
      "Pudu",
      "Hang Tuah",
      "Plaza Rakyat",
      "Masjid Jamek",
      "Bandaraya - UOB",
      "Sultan Ismail",
      "PWTC",
      "Titiwangsa",
      "Sentul",
      "Sentul Timur"
    ]
  },
  {
    "id": "kajang",
    "name": "MRT Kajang Line",
    "stations": [
      "Kwasa Damansara",
      "Kwasa Sentral",
      "Kota Damansara",
      "Surian",
      "Mutiara Damansara",
      "Bandar Utama",
      "Taman Tun Dr Ismail",
      "Phileo Damansara",
      "Pusat Bandar Damansara",
      "Semantan",
      "Muzium Negara",
      "Pasar Seni",
      "Merdeka",
      "Bukit Bintang",
      "Tun Razak Exchange",
      "Cochrane",
      "Maluri",
      "Taman Pertama",
      "Taman Midah",
      "Taman Mutiara",
      "Taman Connaught",
      "Taman Suntex",
      "Sri Raya",
      "Bandar Tun Hussein Onn",
      "Batu 11 Cheras",
      "Bukit Dukung",
      "Sungai Jernih",
      "Stadium Kajang",
      "Kajang"
    ]
  },
  {
    "id": "putrajaya",
    "name": "MRT Putrajaya Line",
    "stations": [
      "Kwasa Damansara",
      "Kampung Selamat",
      "Sungai Buloh",
      "Damansara Damai",
      "Sri Damansara Barat",
      "Sri Damansara Sentral",
      "Sri Damansara Timur",
      "Metro Prima",
      "Kepong Baru",
      "Jinjang",
      "Sri Delima",
      "Kampung Batu",
      "Kentomen",
      "Jalan Ipoh",
      "Sentul Barat",
      "Titiwangsa",
      "Hospital Kuala Lumpur",
      "Raja Uda",
      "Ampang Park",
      "Persiaran KLCC",
      "Conlay",
      "Tun Razak Exchange",
      "Chan Sow Lin",
      "Kuchai",
      "Taman Naga Emas",
      "Sungai Besi",
      "Serdang Raya Utara",
      "Serdang Raya Selatan",
      "Serdang Jaya",
      "UPM",
      "Taman Equine",
      "Putra Permai",
      "16 Sierra",
      "Cyberjaya Utara",
      "Cyberjaya City Centre",
      "Putrajaya Sentral"
    ]
  },
  {
    "id": "monorail",
    "name": "KL Monorail Line",
    "stations": [
      "KL Sentral",
      "Tun Sambanthan",
      "Maharajalela",
      "Hang Tuah",
      "Imbi",
      "Bukit Bintang",
      "Raja Chulan",
      "Bukit Nanas",
      "Medan Tuanku",
      "Chow Kit",
      "Titiwangsa"
    ]
  },
  {
    "id": "brt-sunway",
    "name": "BRT Sunway Line",
    "stations": [
      "Sunway-Setia Jaya",
      "Mentari",
      "Sunway Lagoon",
      "Sunmed",
      "SunU-Monash",
      "South Quay-USJ 1",
      "USJ7"
    ]
  },
  {
    "id": "shah-alam",
    "name": "LRT Shah Alam Line",
    "stations": [
      "Bandar Utama",
      "Kayu Ara",
      "Bandar Utama 11",
      "Damansara Idaman",
      "Subang",
      "Glenmarie 2",
      "Kerjaya",
      "Stadium Shah Alam",
      "Dato' Menteri - SA Sentral",
      "UITM Shah Alam",
      "Seksyen 7",
      "Bandar Baru Klang",
      "Pasar Klang",
      "Jalan Meru",
      "Jambatan Kota",
      "Taman Selatan",
      "Seri Andalas",
      "Klang Jaya",
      "Bandar Bukit Tinggi",
      "Johan Setia"
    ]
  }
] as const;

export type LineId = (typeof LINES)[number]["id"];
