// Generated from two official GTFS static feeds on data.gov.my
// (https://developer.data.gov.my/realtime-api/gtfs-static) via
// scripts/generate-stations.mjs — don't hand-edit, re-run the script
// instead if the source data changes:
//   - Prasarana (category=rapid-rail-kl): LRT, MRT, KL Monorail, BRT Sunway
//   - KTMB: the two Klang Valley Komuter lines only (route_type "0") —
//     Intercity/ETS long-distance routes in the same feed are excluded
//
// arrivalOffsetMinutes[i] is minutes from stations[0]'s departure to
// stations[i]'s arrival, per one representative weekday trip — real
// scheduled timetable data, used for expected-arrival estimates
// (lib/schedule.ts), not live tracking.

export const LINES = [
  {
    "id": "ampang",
    "name": "LRT Ampang Line",
    "color": "#e57200",
    "stations": [
      "Ampang",
      "Cahaya",
      "Cempaka",
      "Pandan Indah",
      "Pandan Jaya",
      "Maluri",
      "Miharja",
      "Chan Sow Lin",
      "Pudu",
      "Hang Tuah",
      "Plaza Rakyat",
      "Masjid Jamek",
      "Bandaraya - UOB",
      "Sultan Ismail",
      "PWTC",
      "Titiwangsa",
      "Sentul",
      "Sentul Timur"
    ],
    "arrivalOffsetMinutes": [
      0,
      2,
      3,
      5,
      6,
      8,
      10,
      12,
      14,
      15,
      16,
      18,
      20,
      22,
      23,
      25,
      26,
      28
    ]
  },
  {
    "id": "kelana-jaya",
    "name": "LRT Kelana Jaya Line",
    "color": "#D50032",
    "stations": [
      "Putra Heights",
      "Subang Alam",
      "Alam Megah",
      "USJ 21",
      "Wawasan",
      "Taipan",
      "USJ 7",
      "SS 18",
      "SS 15",
      "Subang Jaya",
      "Glenmarie",
      "Ara Damansara",
      "Lembah Subang",
      "Kelana Jaya",
      "Taman Bahagia",
      "Taman Paramount",
      "Asia Jaya",
      "Taman Jaya",
      "Universiti",
      "Kerinchi",
      "Abdullah Hukum",
      "Bangsar - Bank Rakyat",
      "KL Sentral",
      "Pasar Seni",
      "Masjid Jamek",
      "Dang Wangi",
      "Kampung Baru - CBP Coopbank Pertama",
      "KLCC",
      "Ampang Park",
      "Damai",
      "Dato' Keramat",
      "Jelatek",
      "Setiawangsa",
      "Sri Rampai",
      "Wangsa Maju",
      "Taman Melati",
      "Gombak"
    ],
    "arrivalOffsetMinutes": [
      0,
      3,
      6,
      10,
      12,
      15,
      17,
      22,
      24,
      27,
      31,
      34,
      36,
      38,
      41,
      43,
      46,
      48,
      51,
      54,
      56,
      58,
      61,
      65,
      68,
      70,
      72,
      75,
      77,
      80,
      82,
      84,
      86,
      90,
      92,
      95,
      98
    ]
  },
  {
    "id": "sri-petaling",
    "name": "LRT Sri Petaling Line",
    "color": "#76232f",
    "stations": [
      "Putra Heights",
      "Puchong Prima",
      "Puchong Perdana",
      "Bandar Puteri",
      "Taman Perindustrian Puchong",
      "Pusat Bandar Puchong",
      "IOI Puchong Jaya",
      "Kinrara",
      "Alam Sutera",
      "Muhibbah",
      "Awan Besar",
      "Sri Petaling",
      "Bukit Jalil",
      "Sungai Besi",
      "Bandar Tasik Selatan",
      "Bandar Tun Razak",
      "Salak Selatan",
      "Cheras",
      "Chan Sow Lin",
      "Pudu",
      "Hang Tuah",
      "Plaza Rakyat",
      "Masjid Jamek",
      "Bandaraya - UOB",
      "Sultan Ismail",
      "PWTC",
      "Titiwangsa",
      "Sentul",
      "Sentul Timur"
    ],
    "arrivalOffsetMinutes": [
      0,
      4,
      7,
      9,
      11,
      13,
      14,
      18,
      21,
      24,
      26,
      28,
      29,
      32,
      34,
      37,
      39,
      41,
      44,
      45,
      47,
      48,
      50,
      52,
      54,
      55,
      57,
      58,
      60
    ]
  },
  {
    "id": "kajang",
    "name": "MRT Kajang Line",
    "color": "#047940",
    "stations": [
      "Kwasa Damansara",
      "Kwasa Sentral",
      "Kota Damansara",
      "Surian",
      "Mutiara Damansara",
      "Bandar Utama",
      "Taman Tun Dr Ismail",
      "Phileo Damansara",
      "Pusat Bandar Damansara",
      "Semantan",
      "Muzium Negara",
      "Pasar Seni",
      "Merdeka",
      "Bukit Bintang",
      "Tun Razak Exchange",
      "Cochrane",
      "Maluri",
      "Taman Pertama",
      "Taman Midah",
      "Taman Mutiara",
      "Taman Connaught",
      "Taman Suntex",
      "Sri Raya",
      "Bandar Tun Hussein Onn",
      "Batu 11 Cheras",
      "Bukit Dukung",
      "Sungai Jernih",
      "Stadium Kajang",
      "Kajang"
    ],
    "arrivalOffsetMinutes": [
      0,
      2,
      6,
      8,
      11,
      14,
      17,
      20,
      24,
      28,
      32,
      36,
      39,
      42,
      46,
      48,
      51,
      54,
      57,
      60,
      64,
      67,
      70,
      73,
      76,
      79,
      83,
      86,
      88
    ]
  },
  {
    "id": "putrajaya",
    "name": "MRT Putrajaya Line",
    "color": "#FFCD00",
    "stations": [
      "Kwasa Damansara",
      "Kampung Selamat",
      "Sungai Buloh",
      "Damansara Damai",
      "Sri Damansara Barat",
      "Sri Damansara Sentral",
      "Sri Damansara Timur",
      "Metro Prima",
      "Kepong Baru",
      "Jinjang",
      "Sri Delima",
      "Kampung Batu",
      "Kentomen",
      "Jalan Ipoh",
      "Sentul Barat",
      "Titiwangsa",
      "Hospital Kuala Lumpur",
      "Raja Uda",
      "Ampang Park",
      "Persiaran KLCC",
      "Conlay",
      "Tun Razak Exchange",
      "Chan Sow Lin",
      "Kuchai",
      "Taman Naga Emas",
      "Sungai Besi",
      "Serdang Raya Utara",
      "Serdang Raya Selatan",
      "Serdang Jaya",
      "UPM",
      "Taman Equine",
      "Putra Permai",
      "16 Sierra",
      "Cyberjaya Utara",
      "Cyberjaya City Centre",
      "Putrajaya Sentral"
    ],
    "arrivalOffsetMinutes": [
      0,
      3,
      5,
      7,
      9,
      11,
      13,
      14,
      16,
      17,
      18,
      20,
      22,
      23,
      25,
      26,
      28,
      29,
      31,
      32,
      33,
      35,
      37,
      43,
      44,
      47,
      49,
      51,
      52,
      54,
      58,
      60,
      62,
      65,
      67,
      68
    ]
  },
  {
    "id": "monorail",
    "name": "KL Monorail Line",
    "color": "#84bd00",
    "stations": [
      "KL Sentral",
      "Tun Sambanthan",
      "Maharajalela",
      "Hang Tuah",
      "Imbi",
      "Bukit Bintang",
      "Raja Chulan",
      "Bukit Nanas",
      "Medan Tuanku",
      "Chow Kit",
      "Titiwangsa"
    ],
    "arrivalOffsetMinutes": [
      0,
      3,
      7,
      9,
      11,
      14,
      16,
      18,
      20,
      23,
      26
    ]
  },
  {
    "id": "brt-sunway",
    "name": "BRT Sunway Line",
    "color": "#115740",
    "stations": [
      "Sunway-Setia Jaya",
      "Mentari",
      "Sunway Lagoon",
      "Sunmed",
      "SunU-Monash",
      "South Quay-USJ 1",
      "USJ7"
    ],
    "arrivalOffsetMinutes": [
      0,
      3,
      6,
      8,
      11,
      13,
      16
    ]
  },
  {
    "id": "shah-alam",
    "name": "LRT Shah Alam Line",
    "color": "#00A9E0",
    "stations": [
      "Bandar Utama",
      "Kayu Ara",
      "Bandar Utama 11",
      "Damansara Idaman",
      "Subang",
      "Glenmarie 2",
      "Kerjaya",
      "Stadium Shah Alam",
      "Dato' Menteri - SA Sentral",
      "UITM Shah Alam",
      "Seksyen 7",
      "Bandar Baru Klang",
      "Pasar Klang",
      "Jalan Meru",
      "Jambatan Kota",
      "Taman Selatan",
      "Seri Andalas",
      "Klang Jaya",
      "Bandar Bukit Tinggi",
      "Johan Setia"
    ],
    "arrivalOffsetMinutes": [
      0,
      2,
      5,
      8,
      11,
      14,
      20,
      23,
      29,
      34,
      37,
      41,
      45,
      47,
      49,
      54,
      56,
      58,
      61,
      66
    ]
  },
  {
    "id": "komuter-seremban",
    "name": "KTM Seremban Line",
    "color": "#3C5A9F",
    "stations": [
      "Batu Caves",
      "Taman Wahyu",
      "Kampung Batu",
      "Batu Kentonmen",
      "Sentul",
      "Putra",
      "Bank Negara",
      "Kuala Lumpur",
      "KL Sentral",
      "Midvalley",
      "Seputih",
      "Salak Selatan",
      "Bandar Tasek (S)",
      "Serdang",
      "Kajang",
      "Kajang 2",
      "UKM",
      "Bangi",
      "Batang Benar",
      "Nilai",
      "Labu",
      "Tiroi",
      "Seremban",
      "Senawang",
      "Sungai Gadut",
      "Rembau",
      "Pulau Sebang (Tampin)"
    ],
    "arrivalOffsetMinutes": [
      0,
      3,
      6,
      8,
      12,
      18,
      21,
      25,
      29,
      37,
      39,
      45,
      51,
      59,
      75,
      79,
      82,
      88,
      100,
      111,
      118,
      124,
      131,
      137,
      143,
      156,
      173
    ]
  },
  {
    "id": "komuter-port-klang",
    "name": "KTM Port Klang Line",
    "color": "#DC2420",
    "stations": [
      "Tanjung Malim",
      "Kalumpang",
      "Kuala Kubu Baru",
      "Rasa",
      "Batang Kali",
      "Serendah",
      "Rawang",
      "Kuang",
      "Sungai Buluh",
      "Kepong Sentral",
      "Kepong",
      "Segambut",
      "Putra",
      "Bank Negara",
      "Kuala Lumpur",
      "KL Sentral",
      "Abdullah Hukum",
      "Angkasapuri",
      "Pantai Dalam",
      "Petaling",
      "Jalan Templer",
      "Kg.Datuk Harun",
      "Seri Setia",
      "Setia Jaya",
      "Subang Jaya",
      "Batu Tiga",
      "Shah Alam",
      "Padang Jawa",
      "Bukit Badak",
      "Klang",
      "Teluk Pulai",
      "Teluk Gadong",
      "Kampung Raja Uda",
      "Jalan Kastam",
      "Pel. Klang (S)"
    ],
    "arrivalOffsetMinutes": [
      0,
      3,
      13,
      18,
      21,
      29,
      38,
      46,
      53,
      61,
      64,
      69,
      74,
      77,
      81,
      85,
      99,
      101,
      105,
      107,
      110,
      115,
      117,
      120,
      124,
      130,
      137,
      143,
      148,
      153,
      166,
      169,
      172,
      174,
      180
    ]
  }
] as const;

export type LineId = (typeof LINES)[number]["id"];
